export { ReactComponent as Plus } from "./Plus.svg"
export { ReactComponent as Exchange } from "./Exchange.svg"
export { ReactComponent as ArrowDown} from "./ArrowDown.svg"
export { ReactComponent as Reset } from "./Reset.svg"
export { ReactComponent as SearchIcon } from "./Search.svg"
export { ReactComponent as Add } from "./Add.svg"
export { ReactComponent as ThinArrow } from "./ThinArrow.svg"
export { ReactComponent as X } from "./X.svg"
export { ReactComponent as Writer } from "./Writer.svg"
export { ReactComponent as Error } from "./Error.svg"
export { ReactComponent as ArrowLeft } from "./ArrowLeft.svg"
export { ReactComponent as ArrowRight } from "./ArrowRight.svg"
export { ReactComponent as Cancel } from "./Cancel.svg"